<<<<<<< HEAD
## Тестування асинхронного коду

Асинхронний код є дуже поширеним в JavaScript. Коли у вас є код, який працює асинхронно, Jest повинен знати, коли код, що тестується, закінчив свою роботу перед тим, як перейти до наступного тесту. Jest дозволяє це зробити кількома способами.

## Зворотні виклики

Найбільш популярним асинхронним паттерном є зворотні виклики.

Наприклад, нехай у вас є функція `fetchData(callback)`, яка отримує дані і викликає `callback(data)`, коли дані отримано. Ви хочете перевірити, що ці повернуті дані є рядком `'peanut butter'`.

За замовчуванням тести Jest завершуються, коли вони досягають кінця свого виконання. Це означає, що цей тест не буде працювати належним чином:

```js
// Don't do this!
test('the data is peanut butter', () => {
  function callback(data) {
    expect(data).toBe('peanut butter');
  }

  fetchData(callback);
});
```

Проблема в тому, що тест закінчується як тільки виконається код функції fetchData, до того, як буде виконано зворотній виклик.

Існує альтернативний вигляд тесту, який це виправляє. Замість того, щоб писати тест в функції без аргументів, використайте аргумент done. В такому випадку Jest чекатиме виконання зворотнього виклику done перед тим, як завершити тест.

```js
test('the data is peanut butter', done => {
  function callback(data) {
    try {
      expect(data).toBe('peanut butter');
      done();
    } catch (error) {
      done(error);
    }
  }

  fetchData(callback);
});
```

Якщо ніколи не викликати done(), тест не вдасться (з помилкою тайм-ауту), саме цього ви і хочете .

Якщо оператор очікування не вдається, він видає помилку, і `done()` не викликається. Якщо ми хочемо побачити в тестовому журналі, чому він не вдався, нам слід обернути `expect`
у блоці `try` та передайте помилку в блоці `catch` до кінця `done`. В іншому випадку ми отримуємо непрозору помилку тайм-ауту, яка не показує, яке значення було
отримав `expect(data)`.

## Проміси

If your code uses promises, there is a more straightforward way to handle asynchronous tests. Return a promise from your test, and Jest will wait for that promise to resolve. Якщо проміс буде відхилений, тест автоматично впаде.

For example, let's say that fetchData, instead of using a callback, returns a promise that is supposed to resolve to the string 'peanut butter'. We could test it with:

```js
test('the data is peanut butter', () => {
  return fetchData().then(data => {
    expect(data).toBe('peanut butter');
  });
});
```

Будьте впевнені що ви повертаєте саме проміс, якщо ви пропустите інструкцію return, ваш тест завершиться до моменту коли проміс з fetchData буде вирішен i then() зможе виповнити свій зворотній виклик.

If you expect a promise to be rejected, use the .catch method. Не забудьте додати expect.assertions щоб переконатися, що певна кількість перевірок була виконана. Otherwise, a fulfilled promise would not fail the test.

test('the fetch fails with an error', () => {
  expect.assertions(1);
  return fetchData().catch(e => expect(e).toMatch('error'));
});

## .resolves/.rejects

Ви також можете використовувати зв’язок `.resolves` у своєму операторі очікування, і Jest буде чекати, поки ця обіцянка вирішиться. Якщо проміс буде відхилений, тест автоматично впаде.

```js
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter');
});
```

Будьте впевнені що ви повертаєте твердження — якщо ви пропустите інструкцію return, ваш тест буде завершено до моменту як проміс повернутий з fetchData буде вирішен та then() зможе виповнити свій зворотній виклик.

Якщо ви очікуєте, що обіцянку буде відхилено, використовуйте `.rejects` матч. Він працює аналогічно матчеру `.resolves`. Якщо проміс буде виконано успішно, це викличе помилку в тесті.

```js
test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error');
});
```

## Async/Await

Окрім того ви можете використовувати `async` та `await` у ваших тестах. Напишемо `async` test, використовувати ключове слово async перед функцією, переданою `test`. Наприкоад, та сама функція `fetchData` може бути протестована так:

```js
test('the data is peanut butter', async () => {
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  expect.assertions(1);
  try {
    await fetchData();
  } catch (e) {
    expect(e).toMatch('error');
  }
});
```

Ви можете поєднати асинхронізацію та очікування з .resolves або .rejects.

```js
test('the data is peanut butter', async () => {
  await expect(fetchData()).resolves.toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  await expect(fetchData()).rejects.toMatch('error');
});
```

У цих випадках, `async` and `await` є фактично синтаксичним цукром для тієї самої логіки, що і в обіцяному прикладі.

=======
## Тестування асинхронного коду

Асинхронний код є дуже поширеним в JavaScript. Коли у вас є код, який працює асинхронно, Jest повинен знати, коли код, що тестується, закінчив свою роботу перед тим, як перейти до наступного тесту. Jest дозволяє це зробити кількома способами.

## Зворотні виклики

Найбільш популярним асинхронним паттерном є зворотні виклики.

Наприклад, нехай у вас є функція `fetchData(callback)`, яка отримує дані і викликає `callback(data)`, коли дані отримано. Ви хочете перевірити, що ці повернуті дані є рядком `'peanut butter'`.

За замовчуванням тести Jest завершуються, коли вони досягають кінця свого виконання. Це означає, що цей тест не буде працювати належним чином:

```js
// Don't do this!
test('the data is peanut butter', () => {
  function callback(data) {
    expect(data).toBe('peanut butter');
  }

  fetchData(callback);
});
```

Проблема в тому, що тест закінчується як тільки виконається код функції fetchData, до того, як буде виконано зворотній виклик.

Існує альтернативний вигляд тесту, який це виправляє. Замість того, щоб писати тест в функції без аргументів, використайте аргумент done. В такому випадку Jest чекатиме виконання зворотнього виклику done перед тим, як завершити тест.

```js
test('the data is peanut butter', done => {
  function callback(data) {
    try {
      expect(data).toBe('peanut butter');
      done();
    } catch (error) {
      done(error);
    }
  }

  fetchData(callback);
});
```

Якщо ніколи не викликати done(), тест не вдасться (з помилкою тайм-ауту), саме цього ви і хочете .

Якщо оператор очікування не вдається, він видає помилку, і `done()` не викликається. Якщо ми хочемо побачити в тестовому журналі, чому він не вдався, нам слід обернути `expect`
у блоці `try` та передайте помилку в блоці `catch` до кінця `done`. В іншому випадку ми отримуємо непрозору помилку тайм-ауту, яка не показує, яке значення було
отримав `expect(data)`.

## Проміси

If your code uses promises, there is a more straightforward way to handle asynchronous tests. Return a promise from your test, and Jest will wait for that promise to resolve. Якщо проміс буде відхилений, тест автоматично впаде.

For example, let's say that fetchData, instead of using a callback, returns a promise that is supposed to resolve to the string 'peanut butter'. We could test it with:

```js
test('the data is peanut butter', () => {
  return fetchData().then(data => {
    expect(data).toBe('peanut butter');
  });
});
```

Будьте впевнені що ви повертаєте саме проміс, якщо ви пропустите інструкцію return, ваш тест завершиться до моменту коли проміс з fetchData буде вирішен i then() зможе виповнити свій зворотній виклик.

If you expect a promise to be rejected, use the .catch method. Не забудьте додати expect.assertions щоб переконатися, що певна кількість перевірок була виконана. Otherwise, a fulfilled promise would not fail the test.

test('the fetch fails with an error', () => {
  expect.assertions(1);
  return fetchData().catch(e => expect(e).toMatch('error'));
});

## .resolves/.rejects

Ви також можете використовувати зв’язок `.resolves` у своєму операторі очікування, і Jest буде чекати, поки ця обіцянка вирішиться. Якщо проміс буде відхилений, тест автоматично впаде.

```js
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter');
});
```

Будьте впевнені що ви повертаєте твердження — якщо ви пропустите інструкцію return, ваш тест буде завершено до моменту як проміс повернутий з fetchData буде вирішен та then() зможе виповнити свій зворотній виклик.

Якщо ви очікуєте, що обіцянку буде відхилено, використовуйте `.rejects` матч. Він працює аналогічно матчеру `.resolves`. Якщо проміс буде виконано успішно, це викличе помилку в тесті.

```js
test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error');
});
```

## Async/Await

Окрім того ви можете використовувати `async` та `await` у ваших тестах. Напишемо `async` test, використовувати ключове слово async перед функцією, переданою `test`. Наприкоад, та сама функція `fetchData` може бути протестована так:

```js
test('the data is peanut butter', async () => {
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  expect.assertions(1);
  try {
    await fetchData();
  } catch (e) {
    expect(e).toMatch('error');
  }
});
```

Ви можете поєднати асинхронізацію та очікування з .resolves або .rejects.

```js
test('the data is peanut butter', async () => {
  await expect(fetchData()).resolves.toBe('peanut butter');
});

test('the fetch fails with an error', async () => {
  await expect(fetchData()).rejects.toMatch('error');
});
```

У цих випадках, `async` and `await` є фактично синтаксичним цукром для тієї самої логіки, що і в обіцяному прикладі.

>>>>>>> 8b195a81277fc363fba4573cae0a1533c8033cba
Жодна з цих форм особливо не перевершує інших, і ви можете змішувати та поєднувати їх у кодовій базі або навіть в одному файлі. Це лише залежить від того, який стиль ви відчуваєте, робить ваші тести простішими.